export const initTreeData = {
  name: '江苏苏美食品有限公司',
  type: 'company',
  children: [
    {
      name: '股东',
      type: 'holders',
      children: [
        {
          name: '上海东证今缘股权投资基金合伙企业',
          type: 'company',
          tags: [],
          tips: '31.25%',
          children: [],
        },
        {
          name: '陈华云',
          type: 'other',
          tags: [],
          tips: '22.83%',
          children: [],
        },
        {
          name: '江苏谷丰农业投资基金',
          type: 'company',
          tags: [],
          tips: '20.81%',
          children: [],
        },
        {
          name: '陈奎',
          type: 'other',
          tags: [],
          tips: '17.79%',
          children: [],
        },
        {
          name: '涟水兴华投资',
          type: 'company',
          tags: [],
          tips: '4.16%',
          children: [],
        },
        {
          name: '南京厚积投资发展中心',
          type: 'company',
          tags: [],
          tips: '1.04%',
          children: [],
        },
        {
          name: '梁俊懿',
          type: 'person',
          tags: [],
          tips: '0.81%',
          children: [],
        },
        {
          name: '周士力',
          type: 'other',
          tags: [],
          tips: '0.64%',
          children: [],
        },
        {
          name: '朱延宏',
          type: 'other',
          tags: [],
          tips: '0.31%',
          children: [],
        },
        {
          name: '姜雷',
          type: 'other',
          tags: [],
          tips: '0.22%',
          children: [],
        },
        {
          name: '陈永正',
          type: 'other',
          tags: [],
          tips: '0.14%',
          children: [],
        },
      ],
    },
    {
      name: '实控人',
      type: 'controller',
      children: [
        {
          name: '江苏省淮安市涟水县人民政府',
          type: 'company',
          tags: [],
          children: [],
        },
      ],
    },
    {
      name: '高管',
      type: 'topmanager',
      children: [
        {
          name: '吴海元',
          type: '',
          tags: [],
          tips: '22.83%',
          children: [],
        },
        {
          name: '周士力',
          type: '',
          tags: [],
          tips: '',
          children: [],
        },
        {
          name: '陈华云',
          type: '',
          tags: [],
          tips: '',
          children: [],
        },
        {
          name: '姚燕杰',
          type: '',
          tags: [],
          tips: '',
          children: [],
        },
        {
          name: '曹海林',
          type: '',
          tags: [],
          tips: '',
          children: [],
        },
        {
          name: '刘立鹏',
          type: 'person',
          tags: [],
          tips: '',
          children: [],
        },
        {
          name: '姜雷',
          type: '',
          tags: [],
          tips: '',
          children: [],
        },
      ],
    },
    {
      name: '供应商',
      type: 'suppliers',
      children: [
        {
          name: '江苏苏盐井神',
          type: 'company',
          tags: [],
          tips: '',
          children: [],
          hasChildren: true,
        },
      ],
    },
  ],
};
