on: push
jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: ['16', '17']
    steps:
      - name: install react 16
        if: ${{ matrix.react == '16' }}
        run: echo "react-16"
      - name: install react 17
        if: ${{ matrix.react == '17' }}
        run: echo "react-17"
